### PR TITLE
Bug: Unchecked serviceName parameter leads to a crash in deploy and deployImage

### LINKED ISSUE #108: Bug: Unchecked serviceName parameter leads to a crash in deploy and deployImage
### Description

The `deploy` and `deployImage` functions in `lib/cloud-run-deploy.js` can crash if the `serviceName` parameter is `undefined`. This happens when the `DEFAULT_SERVICE_NAME` environment variable is not set and no service name is provided in the tool call.

The application has a check for an `undefined` `projectId`, and a similar check should be implemented for `serviceName` to prevent this crash.

### Steps to Reproduce

1.  Unset the `DEFAULT_SERVICE_NAME` environment variable.
2.  Call the `deploy` or `deployImage` tool without providing a `service` parameter.
3.  The application will crash.

### Stack Trace

```
[DEBUG] [MCP STDERR (cloud-run)]:  Checking and enabling required APIs...
[DEBUG] [MCP STDERR (cloud-run)]:  All required APIs are enabled.
[DEBUG] [MCP STDERR (cloud-run)]:  Project: my-project
[DEBUG] [MCP STDERR (cloud-run)]:  Region: europe-west1
Service Name: undefined
Files to deploy: 1
Dockerfile: false
[DEBUG] [MCP STDERR (cloud-run)]:  Bucket my-project-source-bucket already exists.
[DEBUG] [MCP STDERR (cloud-run)]:  Creating in-memory zip archive...
[DEBUG] [MCP STDERR (cloud-run)]:  Files zipped successfully. Total size: 893432 bytes
[DEBUG] [MCP STDERR (cloud-run)]:  Uploading buffer to gs://my-project-source-bucket/source.zip...
[DEBUG] [MCP STDERR (cloud-run)]:  File source.zip uploaded successfully to gs://my-project-source-bucket/source.zip.
[DEBUG] [MCP STDERR (cloud-run)]:  Source code uploaded successfully
[DEBUG] [MCP STDERR (cloud-run)]:  Repository mcp-cloud-run-deployments already exists in europe-west1.
[DEBUG] [MCP STDERR (cloud-run)]:  Initiating Cloud Build for gs://my-project-source-bucket/source.zip in europe-west1...
[DEBUG] [MCP STDERR (cloud-run)]:  Cloud Build job started...
[DEBUG] [MCP STDERR (cloud-run)]:  Build status: WORKING. Waiting...
[DEBUG] [MCP STDERR (cloud-run)]:  Cloud Build job 6ed43bce-760c-4540-8ecd-636bcabf3391 completed successfully.
[DEBUG] [MCP STDERR (cloud-run)]:  Image built: europe-west1-docker.pkg.dev/my-project/mcp-cloud-run-deployments/undefined
[DEBUG] [MCP STDERR (cloud-run)]:  Deployment Failed TypeError: Cannot read properties of undefined (reading 'toString')
    at PathTemplate.render (/path/to/dir/remove-local-files/node_modules/google-gax/build/src/pathTemplate.js:117:37)
    at ServicesClient.servicePath (/path/to/dir/remove-local-files/node_modules/@google-cloud/run/build/src/v2/services_client.js:1243:55)
    at deployToCloudRun (file:///path/to/dir/remove-local-files/lib/cloud-run-deploy.js:135:33)
    at deploy (file:///path/to/dir/remove-local-files/lib/cloud-run-deploy.js:833:27)
    at async file:///path/to/dir/remove-local-files/tools.js:391:28
    at async file:///path/to/dir/remove-local-files/node_modules/@modelcontextprotocol/sdk/dist/esm/server/mcp.js:85:30
Deployment Failed: Cannot read properties of undefined (reading 'toString')
```

### Suggested Solution

Add a check for `serviceName` in both the `deploy` and `deployImage` functions in `lib/cloud-run-deploy.js`, similar to the existing check for `projectId`.

**Current `projectId` check in `lib/cloud-run-deploy.js`:**

```javascript
if (!projectId) {
    const errorMsg =
      'Error: projectId is required in the configuration object.';
    await logAndProgress(errorMsg, progressCallback, 'error');
    process.exit(1);
}
```

**Proposed `serviceName` check:**

```javascript
if (!serviceName) {
    const errorMsg =
      'Error: serviceName is required in the configuration object.';
    await logAndProgress(errorMsg, progressCallback, 'error');
    process.exit(1);
}
```

This check should be added to the beginning of both the `deploy` and `deployImage` functions.

### PR DESCRIPTION
**Pull request by wietsevenema**
Fixes #108

### CODE REVIEW

File: lib/cloud-run-deploy.js [hunk 1]
```diff
@@ -720,6 +720,13 @@ export async function deploy({
     process.exit(1);
   }
 
+  if (!serviceName) {
+    const errorMsg =
+      'Error: serviceName is required in the configuration object.';
+    await logAndProgress(errorMsg, progressCallback, 'error');
+    process.exit(1);
```
Comment (justinmahood) [inline lib/cloud-run-deploy.js]: @wietsevenema I don't think we should kill the process here, we should return the error back through the tool response.  You can see I used a similar pattern for ADC checks in #76

**Review by justinmahood — CHANGES_REQUESTED** [review]

**Comment by wietsevenema** [comment]
@justinmahood sure that makes more sense. I was blindly copying the pattern already in that file. it now throws an error, the MCP SDK knows how to propagate that. Here's an example with Gemini CLI: 
Screenshot 2025-08-25 at 12 58 15
